I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 40, in script
    python:
  File "game/script.rpy", line 43, in <module>
    upper(povname)
NameError: name 'upper' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 40, in script
    python:
  File "/home/corinac/renpy-8.1.3-sdk/renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/corinac/renpy-8.1.3-sdk/renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 43, in <module>
    upper(povname)
NameError: name 'upper' is not defined

Linux-6.5.9-arch2-1-x86_64-with-glibc2.38 x86_64
Ren'Py 8.1.3.23091805
Untitled VN 7.0
Sat Jan 27 06:36:42 2024
